#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace Data { namespace Pdf {
struct IPdfPageDimensions;
enum class PdfPageRotation : int {
	Normal = 0,
	Rotate90 = 1,
	Rotate180 = 2,
	Rotate270 = 3,
};
struct IPdfPageRenderOptions;
struct IPdfPage;
struct PdfPageRenderOptions;
struct PdfPageDimensions;
struct IPdfDocument;
struct PdfPage;
struct IPdfDocumentStatics;
struct PdfDocument;
}}}
} // namespace iso_winrt
