#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace ApplicationModel { namespace UserDataAccounts { namespace SystemAccess {
enum class DeviceAccountServerType : int {
	Exchange = 0,
	Pop = 1,
	Imap = 2,
};
enum class DeviceAccountAuthenticationType : int {
	Basic = 0,
	OAuth = 1,
	SingleSignOn = 2,
};
enum class DeviceAccountSyncScheduleKind : int {
	Manual = 0,
	Every15Minutes = 1,
	Every30Minutes = 2,
	Every60Minutes = 3,
	Every2Hours = 4,
	Daily = 5,
	AsItemsArrive = 6,
};
enum class DeviceAccountMailAgeFilter : int {
	All = 0,
	Last1Day = 1,
	Last3Days = 2,
	Last7Days = 3,
	Last14Days = 4,
	Last30Days = 5,
	Last90Days = 6,
};
enum class DeviceAccountIconId : int {
	Exchange = 0,
	Msa = 1,
	Outlook = 2,
	Generic = 3,
};
struct IDeviceAccountConfiguration;
struct IDeviceAccountConfiguration2;
struct IUserDataAccountSystemAccessManagerStatics;
struct DeviceAccountConfiguration;
struct IUserDataAccountSystemAccessManagerStatics2;
struct UserDataAccountSystemAccessManager;
}}}}
} // namespace iso_winrt
