#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace Security { namespace Credentials { namespace UI {
enum class AuthenticationProtocol : int {
	Basic = 0,
	Digest = 1,
	Ntlm = 2,
	Kerberos = 3,
	Negotiate = 4,
	CredSsp = 5,
	Custom = 6,
};
enum class CredentialSaveOption : int {
	Unselected = 0,
	Selected = 1,
	Hidden = 2,
};
struct ICredentialPickerOptions;
struct CredentialPickerOptions;
struct ICredentialPickerStatics;
struct ICredentialPickerResults;
struct CredentialPickerResults;
struct CredentialPicker;
enum class UserConsentVerifierAvailability : int {
	Available = 0,
	DeviceNotPresent = 1,
	NotConfiguredForUser = 2,
	DisabledByPolicy = 3,
	DeviceBusy = 4,
};
enum class UserConsentVerificationResult : int {
	Verified = 0,
	DeviceNotPresent = 1,
	NotConfiguredForUser = 2,
	DisabledByPolicy = 3,
	DeviceBusy = 4,
	RetriesExhausted = 5,
	Canceled = 6,
};
struct IUserConsentVerifierStatics;
struct UserConsentVerifier;
}}}}
} // namespace iso_winrt
