#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace UI { namespace ViewManagement { namespace Core {
enum class CoreInputViewOcclusionKind : int {
	Docked = 0,
	Floating = 1,
	Overlay = 2,
};
enum class CoreInputViewXYFocusTransferDirection : int {
	Up = 0,
	Right = 1,
	Down = 2,
	Left = 3,
};
struct ICoreInputViewOcclusion;
struct ICoreInputView;
struct ICoreInputViewStatics;
struct ICoreInputView2;
struct CoreInputView;
struct ICoreInputViewOcclusionsChangedEventArgs;
struct CoreInputViewOcclusionsChangedEventArgs;
struct CoreInputViewOcclusion;
struct ICoreInputViewTransferringXYFocusEventArgs;
struct CoreInputViewTransferringXYFocusEventArgs;
}}}}
} // namespace iso_winrt
