#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace Perception { namespace People {
struct IHeadPose;
struct HeadPose;
}}}
} // namespace iso_winrt
