#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace Management { namespace Update {
struct IPreviewBuildsState;
struct PreviewBuildsState;
struct IPreviewBuildsManagerStatics;
struct IPreviewBuildsManager;
struct PreviewBuildsManager;
}}}
} // namespace iso_winrt
