#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace Media { namespace Devices { namespace Core {
struct IVariablePhotoSequenceController;
struct VariablePhotoSequenceController;
struct IFrameExposureCapabilities;
struct FrameExposureCapabilities;
struct IFrameExposureCompensationCapabilities;
struct FrameExposureCompensationCapabilities;
struct IFrameIsoSpeedCapabilities;
struct FrameIsoSpeedCapabilities;
struct IFrameFocusCapabilities;
struct FrameFocusCapabilities;
enum class FrameFlashMode : int {
	Disable = 0,
	Enable = 1,
	Global = 2,
};
struct IFrameFlashCapabilities;
struct FrameFlashCapabilities;
struct IFrameControlCapabilities;
struct IFrameControlCapabilities2;
struct FrameControlCapabilities;
struct IFrameExposureControl;
struct FrameExposureControl;
struct IFrameExposureCompensationControl;
struct FrameExposureCompensationControl;
struct IFrameIsoSpeedControl;
struct FrameIsoSpeedControl;
struct IFrameFocusControl;
struct FrameFocusControl;
struct IFrameFlashControl;
struct FrameFlashControl;
struct IFrameController;
struct IFrameController2;
struct FrameController;
struct ICameraIntrinsicsFactory;
struct ICameraIntrinsics2;
struct ICameraIntrinsics;
struct CameraIntrinsics;
struct IDepthCorrelatedCoordinateMapper;
struct DepthCorrelatedCoordinateMapper;
}}}}
} // namespace iso_winrt
