#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace ApplicationModel { namespace Calls { namespace Provider {
struct IPhoneCallOrigin;
struct IPhoneCallOrigin2;
struct IPhoneCallOrigin3;
struct IPhoneCallOriginManagerStatics;
struct PhoneCallOrigin;
struct IPhoneCallOriginManagerStatics2;
struct PhoneCallOriginManager;
}}}}
} // namespace iso_winrt
