#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace UI { namespace Input { namespace Inking { namespace Core {
struct ICoreInkIndependentInputSource;
struct ICoreInkIndependentInputSourceStatics;
struct CoreInkIndependentInputSource;
enum class CoreWetStrokeDisposition : int {
	Inking = 0,
	Completed = 1,
	Canceled = 2,
};
struct ICoreWetStrokeUpdateEventArgs;
struct CoreWetStrokeUpdateEventArgs;
struct ICoreWetStrokeUpdateSource;
struct ICoreWetStrokeUpdateSourceStatics;
struct CoreWetStrokeUpdateSource;
struct ICoreInkPresenterHost;
struct CoreInkPresenterHost;
struct ICoreIncrementalInkStroke;
struct ICoreIncrementalInkStrokeFactory;
struct CoreIncrementalInkStroke;
}}}}}
} // namespace iso_winrt
