#pragma once
// generated by isopod tools

#include "pre_include.h"

namespace iso_winrt {

// forward types

namespace Windows { namespace Phone { namespace Speech { namespace Recognition {
enum class SpeechRecognitionUIStatus : int {
	Succeeded = 0,
	Busy = 1,
	Cancelled = 2,
	Preempted = 3,
	PrivacyPolicyDeclined = 4,
};
}}}}
} // namespace iso_winrt
